implement the underwater overlay property
IrisShaders/Iris pull request #1056
Opened 2021-12-06 03:49 UTC by maximumpower55

Closes: #129

2021-12-06 05:10 UTC, coderbot16 requested changes
Would it be possible to control this with a method on WorldRenderingPipeline instead?

2021-12-06 08:33 UTC, coderbot16 commented
This is an example of how that might look:

https://github.com/IrisShaders/Iris/blob/528488f7c050d077edd76b0b7974aa14fb5ba9e2/src/main/java/net/coderbot/iris/mixin/MixinEntityRenderDispatcher.java

2021-12-06 08:39 UTC, maximumpower55 commented
> This is an example of how that might look:
> 
> https://github.com/IrisShaders/Iris/blob/528488f7c050d077edd76b0b7974aa14fb5ba9e2/src/main/java/net/coderbot/iris/mixin/MixinEntityRenderDispatcher.java

Will look into this tomorrow

2021-12-06 21:00 UTC, coderbot16 requested changes

2021-12-06 21:00 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinScreenEffectRenderer.java
> +    }
wrong indentation?

2021-12-06 21:02 UTC, maximumpower55 commented on src/main/java/net/coderbot/iris/mixin/MixinScreenEffectRenderer.java
> +    }
![Code_VyMWmCeXyD](https://user-images.githubusercontent.com/62370320/144922041-21ee03ab-22fd-4dbb-b38f-1b2949fda382.png)

i think thats just git

2021-12-07 00:33 UTC, maximumpower55 commented on src/main/java/net/coderbot/iris/mixin/MixinScreenEffectRenderer.java
> +    }
Fixed

2021-12-07 00:59 UTC, coderbot16 approved these changes
Thanks!

2021-12-07 00:59 UTC, merged