Make alpha test overrides use the same system as blend mode overrides
IrisShaders/Iris pull request #1065
Opened 2021-12-07 05:28 UTC by maximumpower55

This Will fix this: #219

2021-12-11 19:56 UTC, coderbot16 requested changes
Thanks, please see comments.

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/gl/blending/AlphaTest.java
> +	private final int func;
Yes

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/gl/blending/AlphaTest.java
> +	public AlphaTest(int func, float reference) {
Yes

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/gl/blending/AlphaTestOverride.java
> +		AlphaTestStorage.restoreBlend();
```suggestion
		AlphaTestStorage.restoreAlpha();
```

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/gl/blending/AlphaTestStorage.java
> +	public static void restoreBlend() {
```suggestion
	public static void restoreAlphaTest() {
```

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/GlStateManagerAccessor.java
> +	static GlStateManager.AlphaState getALPHA_TEST() {
This is probably fine as long as it's consistent with other accessors we do

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinGlStateManager_AlphaTestOverride.java
> +		if(AlphaTestStorage.isAlphaTestLocked()) {
```suggestion
		if (AlphaTestStorage.isAlphaTestLocked()) {
```

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinGlStateManager_AlphaTestOverride.java
> +			AlphaTestStorage.deferAlphaTestToggle(true);
You might have swapped this

2021-12-11 19:56 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinGlStateManager_AlphaTestOverride.java
> +			AlphaTestStorage.deferAlphaTestToggle(false);
You might have swapped this

2021-12-12 05:40 UTC, maximumpower55 commented
I have made most of the requested changes locally but the type change of function has really stumped me

2021-12-12 05:41 UTC, maximumpower55 commented
I can't figure out how to convert a gl id into the alpha test function enum

2021-12-12 06:23 UTC, coderbot16 commented
It might be necessary to add a conversion function from GL id to enum (maybe using a switch / Map) to AlphaTestFunction or whatever the class is.

2021-12-12 06:23 UTC, maximumpower55 commented
How did i not think of that well going to implement

2021-12-12 06:48 UTC, maximumpower55 commented
Made requested changes

2021-12-12 06:50 UTC, coderbot16 approved these changes
Thanks!

2021-12-12 06:51 UTC, merged