Add particles.before.deferred
IrisShaders/Iris pull request #1147
Opened 2022-01-01 16:53 UTC by IMS212

2022-01-01 17:03 UTC, coderbot16 requested changes

2022-01-01 17:03 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/fantastic/MixinLevelRenderer.java
> +		if (Iris.getPipelineManager().getPipeline().isPresent() && Iris.getPipelineManager().getPipelineNullable().shouldRenderParticlesBeforeDeferred()) {
This could be cleaned up with Optional.map / orElse.

2022-01-01 17:03 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/fantastic/MixinLevelRenderer.java
> +		if (Iris.getPipelineManager().getPipeline().isPresent() && !Iris.getPipelineManager().getPipelineNullable().shouldRenderParticlesBeforeDeferred()) {
Same here.

2022-01-01 17:03 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/fantastic/MixinLevelRenderer.java
> +			minecraft.particleEngine.render(poseStack, bufferSource, lightTexture, camera, f);
You should push the textured_lit program here.

2022-01-01 17:07 UTC, IMS212 commented
Fixed.

2022-01-02 06:59 UTC, coderbot16 approved these changes
Thanks!

2022-01-02 06:59 UTC, merged