Bug Fixes and Improvements to the Shader Pack Option GUI
IrisShaders/Iris pull request #1185
Opened 2022-01-09 02:58 UTC by FoundationGames

### This pull request addresses some feedback regarding the Shader Pack Option GUI.
![image](https://user-images.githubusercontent.com/43485105/148667313-00ca19b4-3827-43d5-b932-9667c88d36db.png)
- Right clicking sliders no longer causes them to step backwards like non-slider options
- The Escape key can be used to navigate back in the option menu, as well as back out of the option menu into the pack selection menu
- Shader pack configuration files can be exported and imported in and out of the option menu
- Configuration files can be dragged into the option menu to import them
- Spaghetti code used for various general-purpose buttons throughout the GUI has been unified

2022-01-17 15:35 UTC, IMS212 approved these changes
Looks good to me!

2022-01-17 19:19 UTC, coderbot16 requested changes

2022-01-17 19:19 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/gui/element/widget/SliderElementWidget.java
> +		return false;
Suggestion: Add a comment here saying why this shouldn't defer to the parent - just for anyone reading the code in the future.

2022-01-17 21:02 UTC, FoundationGames commented on src/main/java/net/coderbot/iris/gui/element/ShaderPackOptionList.java
>  				this.screen.applyChanges();
The GUI has jobs that need to be handled on reload, therefore it's required that reloading happen through the GUI (I may add a comment explaining this)

2022-01-18 07:58 UTC, coderbot16 approved these changes
Great work, thanks! The import / export feature is certainly a welcome addition.

2022-01-18 07:58 UTC, merged