Update ru_ru.json
IrisShaders/Iris pull request #1186
Opened 2022-01-09 15:03 UTC by Sushomeister

2022-01-10 06:54 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние рендеринга теней определяет, насколько дальняя местность потенциально может быть визуализирована при проходе теней. Меньшие расстояния озна
Всё хорошо, но конкретно эта строчка должна быть переработана.
В частности, нужно перефразировать "насколько дальняя местность", уж слишком режет слух.
Также для лучшего восприятия я бы заменил "_проход теней_" на "_этап теней_", если допускается отклонение от оригинальной терминологии. 
Ну и фраза "_для пакетов, в которых явно указано расстояние рендеринга_" мне тоже не нравится. Я бы заменил на "_для пакетов шейдеров, в которых жёстко закодировано расстояние рендеринга_".

2022-01-10 07:13 UTC, Felix14-v2 requested changes

2022-01-10 07:13 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние рендеринга теней определяет, насколько дальняя местность потенциально может быть визуализирована при проходе теней. Меньшие расстояния озна
Может, что-то вроде этого?
```suggestion
  "options.iris.shadowDistance.sodium_tooltip": "Расстояние видимости теней определяет, насколько далеко местность может обрабатываться на этапе просчёта теней. Меньшие значения соответствуют меньшей площади, что улучшает частоту кадров. Этот параметр нельзя изменить для пакетов, в которых установлено своё расстояние рендеринга теней. Фактическое расстояние рендеринга ограничено дальностью прорисовки.",
```

2022-01-10 10:25 UTC, Sushomeister commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние рендеринга теней определяет, насколько дальняя местность потенциально может быть визуализирована при проходе теней. Меньшие расстояния озна
Хорошо, спасибо, что поправил меня. Я просто переводил почти дословно, и поэтому получилось такое :)
_В частности, нужно перефразировать "насколько дальняя местность", уж слишком режет слух_ - да, тут я с тобой согласен

2022-01-10 17:24 UTC, Felix14-v2 requested changes
Проверил переводы в игре, нужно кое-что поменять, чтобы улучшить восприятие интерфейса.

2022-01-10 18:02 UTC, Felix14-v2 requested changes

2022-01-10 18:02 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние видимости теней определяет, насколько далеко местность может обрабатываться на этапе просчёта теней. Меньшие значения соответствуют меньшей
Вместе с изменением текста в названии настройки нужно изменить текст в соответствующей ей подсказке. + предлагаю заменить "пакетов" на "шейдеров", звучит  лучше, опять же.

```suggestion
  "options.iris.shadowDistance.sodium_tooltip": "Дальность теней определяет, насколько далеко местность может обрабатываться на этапе просчёта теней. Меньшие значения соответствуют меньшей площади, что улучшает частоту кадров. Этот параметр нельзя изменить для шейдеров, в которых установлено своё расстояние рендеринга теней. Фактическое расстояние рендеринга ограничено дальностью прорисовки.",
```

2022-01-10 18:08 UTC, Felix14-v2 commented
Кстати, ещё в 13 строчке речь идёт о версии, однако дальше употребляется местоимение мужского рода:
"_загрузите подходящую версию Sodium, добавьте его в папку_"

Нужно употребить местоимение "её", так как ранее речь шла именно о версии, а не о Sodium.
"загрузите подходящую версию Sodium, добавьте её в папку"

2022-01-10 18:33 UTC, Sushomeister commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние видимости теней определяет, насколько далеко местность может обрабатываться на этапе просчёта теней. Меньшие значения соответствуют меньшей
Ок, спасибо, всё исправлю

2022-01-17 15:34 UTC, IMS212 commented
Thanks!

2022-01-17 15:34 UTC, merged

2022-02-28 18:26 UTC, coderbot16 commented
I didn't notice this before merging, but translation PRs should *always* be targeted at the `trunk` branch. I'll need to cherry-pick this to trunk so that people on 1.16 & 1.17 get the translations as well.