Render stage support (actually)
IrisShaders/Iris pull request #1195
Opened 2022-01-11 23:27 UTC by IMS212

Mostly clean code, and I've confirmed all sky related render stages work. (Have not confirmed stages relating to outlines)

2022-01-11 23:27 UTC, IMS212 commented
Yes, this fixes SEUS PTGI HRR 3.

2022-01-12 00:15 UTC, IMS212 commented
Everything works except for outline and destroy, will look into this.

2022-01-15 17:17 UTC, coderbot16 requested changes
Looks like this conflicts, and I have a few minor comments. Other than that this looks very nice and is a great improvement over the initial PR.

2022-01-15 17:17 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/pipeline/WorldRenderingPhase.java
> +// TODO: Implement this! Right now, this is just here as a stub so packs depending on the macros compile.
This TODO seems outdated...

2022-01-15 17:38 UTC, IMS212 commented
I've yet to find out the cause of outline and destroy, it seems like we need to set those as the program gets used.

2022-01-15 18:02 UTC, coderbot16 commented
Oh right, anything using the BufferSource can't be done by just injecting around calls in LevelRenderer.

2022-01-15 18:03 UTC, IMS212 commented
Fixed.

2022-01-15 18:12 UTC, coderbot16 approved these changes
Looks good, thanks!

2022-01-15 18:12 UTC, merged