Update to 1.18.2
IrisShaders/Iris pull request #1231
Opened 2022-01-21 16:11 UTC by IMS212

Requires CaffeineMC/sodium-fabric#1148 first.

2022-02-02 22:22 UTC, coderbot16 requested changes

2022-02-02 22:22 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinLevelRenderer.java
> +	private void iris$renderSky$tiltSun(PoseStack poseStack, Matrix4f matrix4f, float f, Camera camera, boolean bl, Runnable runnable, CallbackInfo ci) {
matrix4f -> projectionMatrix?

2022-02-02 22:22 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/uniforms/FogUniforms.java
> +			uniforms.uniform1i(UniformUpdateFrequency.ONCE, "fogShape", FogShape.CYLINDER::getIndex);
I don't like the idea of not defining what this means ourselves & just passing through the vanilla enum, especially if the vanilla enum changes.

2022-02-02 22:22 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/uniforms/FogUniforms.java
> +			uniforms.uniform1i(PER_FRAME, "fogShape", RenderSystem.getShaderFogShape()::getIndex);
Ditto.

2022-02-02 22:31 UTC, IMS212 commented
I've fixed the projectionMatrix name everywhere, as well as fogShape by defining 0 as cylindrical and 1 as spherical.

2022-02-02 22:42 UTC, coderbot16 commented
I think it would make the most sense to define 0 to be spherical and 1 to be cylindrical. The uniform will be set to the default value 0 on older versions of Iris and OptiFine, which matches existing shader behavior - spherical fog.

2022-02-02 22:44 UTC, IMS212 commented
Sounds good

2022-02-03 04:30 UTC, coderbot16 commented
I imagine we can leave the default fogShape as 0 when fog is disabled, not that shaders should be relying on any value when fog is disabled.

2022-02-03 04:42 UTC, IMS212 commented
Some shaders may depend on fogShape in the future when there’s no fog, so not sure. It might be safe to just keep it like this

2022-02-03 04:49 UTC, coderbot16 commented
If there's no fog why would they need the shape of it?

2022-02-03 04:54 UTC, IMS212 commented
Shader’s like Xordev’s default may end up assuming fogShape == 0 means “in water” (bad assumption, but still possible), so fogShape == 1 would counter that.

2022-02-03 05:02 UTC, coderbot16 commented
Well fogShape means whatever we want it to mean so we don't have to deal with that kind of legacy weirdness

2022-02-03 14:19 UTC, IMS212 commented
Can we default to -1 for no fog?

2022-02-03 15:41 UTC, coderbot16 commented
That could work

2022-02-21 00:43 UTC, IMS212 commented
This is scheduled to be merged on Feb. 27, one day before the release of 1.18.2.

2022-02-21 03:09 UTC, coderbot16 commented
This doesn't look mergeable - it conflicts with the development branch & we don't know when the next Sodium version will be out.

2022-02-21 03:11 UTC, IMS212 commented
Resolved the conflict, but Sodium is still an issue, yes.

2022-02-28 18:35 UTC, coderbot16 reviewed
The changes here look fine but this cannot be merged until Sodium is updated. I guess people will just have to wait a bit to use shaders on 1.18.2, not a huge deal overall.

2022-03-02 14:02 UTC, IMS212 commented
Should we still have this merged, or just keep the 1.18.2 branch as-is?

2022-03-09 04:34 UTC, coderbot16 commented
We can keep the 1.18.2 branch and remove the 1.18 branch, since it's been superseded.

2022-03-09 04:34 UTC, closed without merging