Entity XHFP vertex format
IrisShaders/Iris pull request #1301
Opened 2022-03-04 09:55 UTC by IMS212

Fixes the major performance regressions, high priority. Code needs to be cleaned up but should otherwise be good.

2022-03-08 22:40 UTC, OroArmor approved these changes
Looks good

2022-03-09 04:27 UTC, coderbot16 requested changes

2022-03-09 04:27 UTC, coderbot16 commented on src/main/resources/iris.accesswidener
> +accessible	class	net/minecraft/client/model/geom/ModelPart$Vertex
Are these still needed?

2022-03-09 04:27 UTC, coderbot16 commented on src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/QuadViewEntity.java
> +	}
I'm not sure if putting this behind a branch is the best approach for performance, maybe we should just have a subclass? I guess we could check the generated assembly to see if this is getting optimized out or not though

2022-03-09 04:27 UTC, coderbot16 commented on src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/writer/EntityVertexBufferWriterNio.java
> +			buffer.putFloat(i - 8 - STRIDE * vertex, midV / 4F);
No need to divide these repeatedly inside the loop, also `* 0.25F` would work

2022-03-09 04:27 UTC, coderbot16 commented on src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/writer/EntityVertexBufferWriterUnsafe.java
> +			MemoryUtil.memPutFloat(i - 8 - STRIDE * vertex, midV / 4F);
Ditto

2022-03-09 04:27 UTC, coderbot16 commented on src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/impl/vertex_format/terrain_xhfp/QuadViewTerrain.java
> +	// TODO: Verify that this works with the new changes to the CVF
I think that this can go away at this point

2022-03-09 04:29 UTC, IMS212 commented on src/main/java/net/coderbot/iris/vertices/IrisVertexFormats.java
> +		TANGENT_ELEMENT = new VertexFormatElement(13, VertexFormatElement.Type.INT, VertexFormatElement.Usage.GENERIC, 1);
How would we reasonably solve this? I have not tested this without Sodium due to buildscript issues, however I can try.

2022-03-09 04:45 UTC, IMS212 commented
Fixed

2022-03-10 02:10 UTC, merged