Updating some translations for Brazilian Portuguese
IrisShaders/Iris pull request #1761
Opened 2022-12-01 14:06 UTC by Draacoun

Fixing translations errors, message formats and more.

2022-12-01 14:33 UTC, rafaeeelv requested changes

2022-12-01 14:33 UTC, rafaeeelv commented on src/main/resources/assets/iris/lang/pt_br.json
> +  "iris.shaders.toggled": "Sombreadores alternado para %s!",
```suggestion
  "iris.shaders.toggled": "Sombreadores alternados para %s!",
```

2022-12-01 14:33 UTC, rafaeeelv commented on src/main/resources/assets/iris/lang/pt_br.json
> +  "iris.shaders.debug.failure": "Não foi possível ativar a depuração pois seu computador não suporta os recursos de depuração.",
```suggestion
  "iris.shaders.debug.failure": "Não foi possível ativar a depuração pois seu computador não suporta os recursos necessários.",
```

2022-12-05 03:14 UTC, IMS212 commented
Would you mind rebasing this on trunk?

2022-12-05 10:23 UTC, Draacoun commented
> Would you mind rebasing this on trunk?

Well, I'm don't use GitHub too often so I don't think I made the right change in this pull request. 😅 

The correct order to rebase this for trunk branch is in fact the edit button in the title? Sorry if this is a dumb question, I really don't know.
![image](https://user-images.githubusercontent.com/47063486/205613622-4645312b-e2c2-4d85-814a-fbb47aaded03.png)

2022-12-05 12:14 UTC, closed without merging