Add Reloading Shaders
IrisShaders/Iris pull request #29
Opened 2020-12-24 01:31 UTC by OverlordsIII

Adds a reloading shaders option for shaderpacks. By default, it is toggled to `R`

2020-12-24 02:03 UTC, OverlordsIII commented
I'm not sure why github actions are not even running, could that be because of the new branch change?

2020-12-26 22:47 UTC, coderbot16 requested changes

2020-12-26 22:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +import java.util.Objects;
Please don't reorder all of the imports unnecessarily.

Importing this code style should help:

```xml
<code_scheme name="Default" version="173">
  <option name="OTHER_INDENT_OPTIONS">
    <value>
      <option name="USE_TAB_CHARACTER" value="true" />
    </value>
  </option>
  <JavaCodeStyleSettings>
    <option name="CLASS_COUNT_TO_USE_IMPORT_ON_DEMAND" value="999" />
    <option name="NAMES_COUNT_TO_USE_IMPORT_ON_DEMAND" value="999" />
    <option name="PACKAGES_TO_USE_IMPORT_ON_DEMAND">
      <value />
    </option>
    <option name="IMPORT_LAYOUT_TABLE">
      <value>
        <package name="" withSubpackages="true" static="true" />
        <emptyLine />
        <package name="java" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="javax" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="net.minecraft" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="net.fabricmc" withSubpackages="true" static="false" />
      </value>
    </option>
  </JavaCodeStyleSettings>
  <editorconfig>
    <option name="ENABLED" value="false" />
  </editorconfig>
  <codeStyleSettings language="Groovy">
    <indentOptions>
      <option name="USE_TAB_CHARACTER" value="true" />
    </indentOptions>
  </codeStyleSettings>
  <codeStyleSettings language="JAVA">
    <indentOptions>
      <option name="CONTINUATION_INDENT_SIZE" value="4" />
      <option name="USE_TAB_CHARACTER" value="true" />
    </indentOptions>
  </codeStyleSettings>
</code_scheme>
```

2020-12-26 22:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +			while (reloadKeybind.wasPressed()){
Why `while`?

2020-12-26 22:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +				.orElseThrow(() -> new RuntimeException("Failed to get the mod container for Iris!")).getRootPath();
No need to mess with the indentation here

2020-12-26 22:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +		currentPack = pack;
I'm going to assume that this code is duplicated, I would prefer for it to not be duplicated

2020-12-26 22:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +
```suggestion
```

2020-12-28 07:19 UTC, coderbot16 commented
Merged via https://github.com/IrisShaders/Iris/commit/967fe3e52b1faa2dfc601046577efc390506b820

2020-12-28 07:19 UTC, closed without merging