Persian Translations
IrisShaders/Iris pull request #298
Opened 2021-05-27 14:41 UTC by alirezaahani

Translation for Persian.
I couldn't find any word that meant " shader pack " in Persian and still made sense to most people so I didn't translate it .
Also names like "Iris" never get translated.

2021-05-28 10:14 UTC, maxigator requested changes

2021-05-28 10:14 UTC, maxigator commented on src/main/resources/assets/iris/lang/fa_ir.json
> +  "options.iris.shaderPackSelection.title": "Shader Packs",
If you don't change the translation you can remove these lines too

2021-05-28 10:14 UTC, maxigator commented on src/main/resources/assets/iris/lang/fa_ir.json
> +  "iris.keybinds": "Iris",
If you don't change the translation you can remove this line

2021-05-28 10:55 UTC, alirezaahani reviewed
Thanks.

2021-05-31 15:49 UTC, coderbot16 approved these changes
Thanks!

2021-05-31 15:49 UTC, merged