Issue forms for Iris
IrisShaders/Iris pull request #429
Opened 2021-06-26 10:21 UTC by altrisi

This PR adds some of the brand new [Github Issue Forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) for the Iris repo.

Issue forms are similar to issue templates in a way, but they are a lot more end-user friendly, since they have proper inputs, textboxes, helper texts, placeholders, selections and checkboxes, and everything gets converted to a nice issue when being submitted.

Not only that, they also allow making some fields required, which is something quite useful IMO to prevent people just skipping the whole template and just writing something like "the game crashes" at the bottom. It also doesn't include the helper texts when the issue is submitted, only the titles and content, making it faster to read even if the user forgot to remove those parts of the templates.

This PR converts the bug report and crash templates into issue forms, having more or less the same fields those had.

You can test those issue forms on the [issue tracker of my Iris fork](https://github.com/altrisi/Iris/issues/new/choose), feel free to spam it with tests.

Feel free to mark as ready and merge it as it currently is. The reason this is a draft is because the current log/crash report section doesn't support attaching files, just pasting, since it seems there is a limitation if the `render` attribute is set (see and upvote github/feedback#4345 and/or github/feedback#4291). It can, however, be changed to a regular textarea if desired.

2021-06-26 11:15 UTC, NoComment1105 approved these changes
Personally i think this is better then the templates i added a couple weeks ago because still ive seen people disregarding the template :/, just a question though, is there not one for feature requests or did you just choose to leave it out?

2021-06-26 11:21 UTC, altrisi commented
I left feature requests since I didn't think they would really benefit of a form, I think they are already nice as templates and not an obligation of how to make them, plus there's not really much extra info needed for a feature request (in a sense of making it required or using some of these new features).

I can add a form for them if you think it's worth it.

2021-06-26 11:23 UTC, NoComment1105 commented
No it's fine, just wondering

2021-06-26 11:29 UTC, yitzy299 requested changes

2021-06-26 11:29 UTC, yitzy299 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      options:
So I'd suggest the following here:

### Iris Version

*String* 

Do you have sodium installed?

*yes | no*

2021-06-26 11:29 UTC, yitzy299 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: textarea
Should have Java version here

2021-06-26 11:29 UTC, yitzy299 commented on .github/ISSUE_TEMPLATE/crash_report.yml
> +      label: Crash Report file or latest.log
So for crash reports both the log and crash report will be useful

2021-06-27 04:24 UTC, merged

2021-06-27 04:26 UTC, coderbot16 commented
This PR seems to be broken? It has zero commits in it.

2021-06-27 06:16 UTC, yitzy299 commented
THe bot seemed to force push removing them...

2021-06-27 10:27 UTC, altrisi commented
Crap I forgot to disable the fork updater...

Will make another one at some point.