Full Physics Mod compatibility, alongside mod loading checks.
IrisShaders/Iris pull request #624
Opened 2021-07-24 22:22 UTC by IMS212

This changes the behavior of Iris to only check for Sodium/PhysicsMod once while the game loads and store it in a static variable, and not to check it during gameplay. This also changes the LivingEntityRenderer mixin to not activate a red tint when an entity is about to die if Physics Mod is installed, as not doing this causes unintended side effects.

2021-07-24 22:51 UTC, IMS212 commented
Turns out there are still some issues. Disabling and re-enabling shaders causes tons of logspam, of OpenGL 1282 errors stating the array object is inactive.

2021-08-04 04:03 UTC, IMS212 commented
These issues have been fixed on Physics Mod's side, and this should be ready for review.

2021-08-20 21:36 UTC, IMS212 commented
Marking this as high priority as without this PR, Physics mod compatibility will break in the next update to Iris.

2021-08-30 17:42 UTC, coderbot16 requested changes
Looks good aside from a few minor encapsulation issues.

2021-08-30 17:42 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +	public static boolean internal;
This has no need to be public.

2021-08-30 17:42 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/Iris.java
> +	public static boolean physicsModInstalled;
These should be private, but have getter methods.

2021-08-30 18:00 UTC, IMS212 commented
All of the issues you brought up should be fixed in the newest commit.

2021-08-30 21:26 UTC, coderbot16 approved these changes
Thanks!

2021-08-30 21:26 UTC, merged