Add External Shaderpack support and add cloud/block outline shaders
IrisShaders/Iris pull request #8
Opened 2020-11-07 23:45 UTC by OverlordsIII

This pr adds external shaderpack support and adds a couple of new shaders for clouds and block outlines.
 * If this pr is accepted, when you start up minecraft, Iris will crash asking you to change your shaderpack in `config/iris.properties`. Simply change the end value of `shaderpack` to be the unzipped folder of the shaderpack. Make sure that the unzipped shaderpack has the `shader` directory directly inside of it.
* It also adds shaders for clouds and block outlines (basic)
* adds parsing of `item.properties` files and `block.properties` files in shaderpacks. Will be used later for uniforms and attributes. Can return the item and block map by calling `Iris.getShaderParser().getItemProperties()` or `Iris.getShaderParser().getBlockProperties()`

I probably messed something up, so please tell me what is wrong so I can fix it.
Thanks for letting me pr on this project.

2020-11-08 00:33 UTC, IMS212 requested changes
you should probably catch if the shaderpack is missing and provide a more user friendly message, and allow the user to change the file to load instead of hardcoding it to gbuffers_basic

2020-11-08 00:48 UTC, IMS212 commented
Otherwise, outside the already known water issue, the Trippy shaderpack seems to work fine.

2020-11-08 01:13 UTC, coderbot16 requested changes
Thanks for the PR! I've left some comments from a first pass over the code.

In general I prefer for PRs to be split up into one PR per logical feature. I think the external shaderpack loading is a good improvement, but I have a different approach that I'd like to take for the clouds / outline shaders. I'll test it out locally and then push it, then the PR can be modified accordingly.

2020-11-10 22:36 UTC, ColdIce1605 commented
I've made some changes to this pr to reflect the changes requested but I don't want to summit a pr for it because of obvious reasons(ripping off it).
its also updated so there is no merge conflicts.

2020-11-11 00:20 UTC, OverlordsIII commented
So this pr is pretty much done, I just have to figure out how to fix the block outline shaders from not working properly, but besides that I've implemented all the changes you requested.

2020-11-11 02:13 UTC, ColdIce1605 commented
hahahaha lmao

2020-11-11 02:14 UTC, OverlordsIII commented
> hahahaha lmao

I definitely have no idea what you are talking about lol

2020-11-11 02:17 UTC, ColdIce1605 commented
I've thought you left this pr, sorry. So I started to solve the problems with this pr.

2020-11-11 02:19 UTC, OverlordsIII commented
> I've thought you left this pr, sorry. So I started to solve the problems with this pr.
oh uhh
i guess that's what you get when you never commit anything till its done lol

2020-11-11 02:22 UTC, ColdIce1605 commented
yeah

2020-11-11 02:33 UTC, ColdIce1605 commented
once this pr is accepted 
I'll do a follow up that adds Logging for errors for shader devs and just the mod itself

2020-11-11 02:43 UTC, OverlordsIII commented
Okay that makes sense
I feel a little wierd using println in this mod too
I think i'll also probably remove the outline shaders from this pr and focus on external loading

2020-11-11 15:17 UTC, ColdIce1605 commented
Is it suppose to compile?

2020-11-11 16:00 UTC, OverlordsIII commented
Umm yea it’s supposed to compile unless I did something really bad.... what is it saying?

2020-11-11 17:32 UTC, ColdIce1605 commented
`C:\Users\James_R\Documents\Projects\Iris-master\src\main\java\net\coderbot\iris\mixin\MixinWorldRenderer.java:94: error: cannot find symbol
                Iris.getPipeline().beginBasic();
                                  ^
  symbol:   method beginBasic()
  location: class ShaderPipeline
C:\Users\James_R\Documents\Projects\Iris-master\src\main\java\net\coderbot\iris\mixin\MixinWorldRenderer.java:98: error: cannot find symbol
                Iris.getPipeline().endBasic();
                                  ^
  symbol:   method endBasic()
  location: class ShaderPipeline
Note: C:\Users\James_R\Documents\Projects\Iris-master\src\main\java\net\coderbot\iris\pipeline\ShaderPipeline.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
`

2020-11-11 18:44 UTC, OverlordsIII commented
Oops uh it should work now... sorry about that

2020-11-11 20:05 UTC, ColdIce1605 commented
https://imgur.com/syN7X2A
first time its worked for me.

2020-11-11 22:51 UTC, ColdIce1605 commented
I know this is a little outta scope(PropertiesParser) but optifine shaders also have shader.properties this should also be under the PropertiesParser class.

2020-11-11 22:52 UTC, OverlordsIII commented
> I know this is a little outta scope(PropertiesParser) but optifine shaders also have shader.properties this should also be under the PropertiesParser class.

Yeah i am actually going to add it today or tomorrow, just trying to see what all the options are

2020-11-11 22:54 UTC, ColdIce1605 requested changes
some things need to be added in PropertiesParser.java

2020-11-11 22:54 UTC, ColdIce1605 commented on src/main/java/net/coderbot/iris/shaderpack/PropertiesParser.java
> +        parseItemProperties();
add shaderProperties per optifine's spec.

2020-11-12 00:03 UTC, coderbot16 commented
I'd rather not expand the scope of this PR too much, please. Just the block and item properties parsing is fine for now.

2020-11-12 00:05 UTC, OverlordsIII commented
> I'd rather not expand the scope of this PR too much, please. Just the block and item properties parsing is fine for now.

ok yea, sorry about that. I'll just table it for now

2020-11-12 15:46 UTC, ColdIce1605 commented
anything keeping this pr from being merged?

2020-11-12 19:01 UTC, WalkerKnapp requested changes
I just suggested a few formatting changes, but how `IrisConfig` is setup is confusing.

2020-11-12 19:02 UTC, OverlordsIII commented on src/main/java/net/coderbot/iris/pipeline/ShaderPipeline.java
> +;
Its my ide, it keeps rearranging the imports whenever I open up a class... It's really annoying. I'll try to disable it

2020-11-12 19:29 UTC, OverlordsIII commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +    private Map<String, Boolean> boolEntries = Maps.newHashMap();
Its just set up that way so you wouldn't need to cast to make sure your object is actually that object. For other objects there will then be another map or properties object for just objects that you could use for things like shaderpath

2020-11-12 19:53 UTC, ColdIce1605 commented on src/main/java/net/coderbot/iris/pipeline/ShaderPipeline.java
> +		basic.use();
why not also do that for texturedLit

2020-11-12 20:02 UTC, WalkerKnapp commented on src/main/java/net/coderbot/iris/pipeline/ShaderPipeline.java
> +		basic.use();
Hm, it looks like all of the methods in `ShaderPipeline` are structured like that. Not sure why, but it's probably best to not change it.

2020-11-13 21:34 UTC, OverlordsIII commented on src/main/java/net/coderbot/iris/Iris.java
> +		ShaderProperties properties = new ShaderProperties().setDefaultPack("Vaporwave-Shaderpack-master");
should be fixed by now

2020-11-14 22:38 UTC, OverlordsIII commented
uh just got the shaders for the outline of the block to work. sorry that i couldn't get it in earlier

2020-11-15 19:47 UTC, coderbot16 requested changes

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +        });
No need to iterate over every property, just query the one that you want.
```suggestion
        this.shaderpath = Paths.get(properties.getProperty("shaderpack", "internal"));
```

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +                System.out.println("falling back to internal shaders...");
Use System.err?

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +            if (!shaderpath.endsWith("internal")) {
Why not equals?

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +        if (!shaderpath.toFile().exists()){
Avoid toFile whenever possible! Use the correct method in [`Files`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html) instead. As far as I know, attempting to convert a valid Path to a File when the Path is ie. in a custom filesystem (like inside a jar file) will crash.

In this case, use `File#exists`.

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +                    .orElseThrow(() -> new RuntimeException("Iris doesnt exists anymore I guess")).getRootPath();
```suggestion
                    .orElseThrow(() -> new RuntimeException("Failed to get the mod container for Iris!")).getRootPath();
```

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +        properties.store(Files.newOutputStream(propertiesPath), "This file is used to parse Iris Shader config options");
```suggestion
        properties.store(Files.newOutputStream(propertiesPath), "This file stores configuration options for Iris, such as the currently active shaderpack");
```

2020-11-15 19:47 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/config/IrisConfig.java
> +    }
I think that the internal shaders should always be the default, this method probably doesn't need to be exposed publicly.

2020-11-16 01:04 UTC, WalkerKnapp approved these changes
Everything I had comments on looks good 👍

2020-11-16 05:10 UTC, coderbot16 requested changes
A few small changes. I also see some assorted minor stylistic issues throughout the PR, but I'll just fix them myself. Once these remaining things are addressed the PR will be good to go!

2020-11-16 17:05 UTC, coderbot16 approved these changes
Looks good to me, thanks!

2020-11-16 17:05 UTC, merged