Update Russian language for Iris 1.1.2
IrisShaders/Iris pull request #840
Opened 2021-09-06 09:24 UTC by Disguys

2021-09-06 09:59 UTC, Felix14-v2 commented
As a native speaker of the Russian language, I ask you: please, close this pool-request. The previous translation was perfect  (except for "Откройте папку c шейдером...", 8th line).

2021-09-06 10:51 UTC, Felix14-v2 commented
Correct localization: 
[ru_ru.zip](https://github.com/IrisShaders/Iris/files/7115377/ru_ru.zip)

2021-09-06 12:11 UTC, Disguys commented
@Felix14-v2 very good, I own it too. If you have any suggestions for translation use request changes button, will be easier. 
![image](https://user-images.githubusercontent.com/60795989/132215319-98a67ab1-0850-46d0-8f26-db97583c8eb8.png)

2021-09-06 12:34 UTC, Felix14-v2 requested changes
Wow, this feature is possible... Let's try!
[ru_ru.zip](https://github.com/IrisShaders/Iris/files/7115982/ru_ru.zip)

2021-09-06 13:12 UTC, Felix14-v2 requested changes
Maybe this try will be successful...

2021-09-06 13:17 UTC, Felix14-v2 requested changes
Hooray, I finally figured it out. Sorry for the spam above, I'm just learning :)

Here is a list of phrases that I recommend changing:

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "iris.keybind.shaderPackSelection": "Экран выбора шейдеров",
```suggestion
  "iris.keybind.shaderPackSelection": "Меню выбора шейдеров",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "iris.sodium.failure.reason": "У вас есть Sodium в папке с модами, но Iris включает его. Закройте игру и удалите Sodium из папки модов.",
```suggestion
  "iris.sodium.failure.reason": "У вас есть Sodium в папке с модами, однако Iris уже содержит его. Пожалуйста, закройте игру и удалите Sodium из папки модов.",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.refreshShaderPacks": "Обновить список шейдеры",
```suggestion
  "options.iris.refreshShaderPacks": "Обновить список шейдеров",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shaderPackSelection.addedPack": "Добавлен шейдерный пакет \"%s\"",
```suggestion
  "options.iris.shaderPackSelection.addedPack": "Добавлен пакет шейдеров \"%s\"",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shaderPackSelection.addedPacks": "Добавлено %s шейдерных пакетов",
```suggestion
  "options.iris.shaderPackSelection.addedPacks": "Добавлено %s пакетов шейдеров",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shaderPackSelection.failedAdd": "Файлы не явились действующими пакетами шейдеров",
```suggestion
  "options.iris.shaderPackSelection.failedAdd": "Файлы не являются допустимыми пакетами шейдеров",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shaderPackSelection.copyError": "Не удалось добавить шейдерный пакет \"%s\"",
```suggestion
  "options.iris.shaderPackSelection.copyError": "Не удалось добавить пакет шейдеров \"%s\"",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance": "Максимальное расстояние теней",
```suggestion
  "options.iris.shadowDistance": "Дальность теней",
```
The phrase is shortened to avoid overlapping with the distance slider

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.disabled": "В вашем текущем шейдерном пакете уже установлено расстояние рендера для теней; вы не можете изменить это.",
```suggestion
  "options.iris.shadowDistance.disabled": "В вашем текущем пакете шейдеров уже установлено расстояние отрисовки теней; вы не можете изменить это.",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.enabled": "Позволяет изменить максимальное расстояние для теней. Ландшафт и объекты за пределами этого расстояния не будут отбрасывать тени. Уменьшение расстояния между
```suggestion
  "options.iris.shadowDistance.enabled": "Позволяет изменить максимальное расстояние для теней. Местность и сущности за пределами этого расстояния не будут отбрасывать тени. Уменьшение дальности может значительно повысить производительность.",
```

2021-09-06 13:17 UTC, Felix14-v2 commented on src/main/resources/assets/iris/lang/ru_ru.json
> +  "options.iris.shadowDistance.sodium_tooltip": "Расстояние отрисовки теней определяет, насколько далеко может быть отрисована местность в проходе теней. Меньшее расстояние означает, что будет отобра
```suggestion
  "options.iris.shadowDistance.sodium_tooltip": "Расстояние отрисовки теней определяет, как далеко потенциально может быть отрисована местность в процессе обработки теней. Меньшие расстояния приводят к сокращению учитываемой территории, что улучшает частоту кадров. Этот параметр нельзя изменить для пакетов шейдеров, в которых уже задано фиксированное расстояние отрисовки теней. Фактическое расстояние отрисовки теней ограничено настройкой общей дальности прорисовки.",
```

2021-09-06 14:04 UTC, Disguys commented
@Felix14-v2 everything is ready, thanks for helping.

2021-11-28 22:07 UTC, merged

2021-11-28 22:21 UTC, IMS212 commented
Thanks!