Geometry shader support in Vanilla
IrisShaders/Iris pull request #970
Opened 2021-11-14 02:57 UTC by IMS212

commit names got messed up, sorry (would probably be smart to squash)

Patching is extremely broken, but the shader gets attached.

2021-12-12 04:34 UTC, coderbot16 requested changes
A few small comments. Also, what do you mean by "patching is extremely broken"?

2021-12-12 04:34 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinProgramManager.java
> +	private static void closeGeometryShader(Shader shader, CallbackInfo ci) {
iris$

2021-12-12 04:34 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinShaderInstance.java
> +	private void attachGeometryShader(CallbackInfo ci) {
iris$

2021-12-12 04:34 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/pipeline/newshader/ExtendedShader.java
> +	public Program getGeometry() {
Probably want either a Nullable annotation or Optional here.

2021-12-12 04:38 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/pipeline/newshader/TriforcePatcher.java
> +		if (source == null) {
We shouldn't be passing null in the first place

2021-12-13 20:11 UTC, IMS212 commented
The patcher somehow just gives up and doesn't patch properly, leading to shader compile failures.

2021-12-13 20:31 UTC, IMS212 commented
Not specifically, but I do know it effects seus ptgi, which patches perfectly with Sodium

2021-12-21 20:18 UTC, coderbot16 commented
Marking as a draft due to the aforementioned issues & merge conflicts.

2022-01-31 02:45 UTC, closed without merging