Support for getNightVisionScale injections
IrisShaders/Iris pull request #988
Opened 2021-11-17 21:32 UTC by Mourdraug

These changes allow nightvision to work for mods which achieve it by directly injecting code into getNightVisionScale (For example [Origins](https://github.com/apace100/apoli/blob/320b0ef547fbbf703de7154f60909d30366f6500/src/main/java/io/github/apace100/apoli/mixin/GameRendererMixin.java#L153)) 
This also means that non binary nightVision values are now possible.

2021-11-17 21:37 UTC, AlsoSylv approved these changes
Everything looks good to me

2021-11-22 04:50 UTC, coderbot16 requested changes
This is a nice start, however, I think we could do better with a different injection. It seems like Origins 1.16.x injects into LightTexture (mojmap) / LightmapTextureManager (yarn), so we could instead maybe use a local variable capture in LightTexture to get the night vision value and store that somewhere, then pass that value to shaders in CommonUniforms.

Obviously local variable captures are fragile, and the injection has to be a bit precise, but I think they might be better here. Alternatively, we can have a separate GameRenderer mixin with a different priority that would guarantee that it applies before the mixin from Origins.

2021-11-22 04:50 UTC, coderbot16 commented on src/main/java/net/coderbot/iris/mixin/MixinGameRenderer.java
> +		if(livingEntity.getEffect(MobEffects.NIGHT_VISION) == null){
This injection could apply before Origins, and might actually break the effect in the mod completely.

2021-12-16 07:42 UTC, merged

2021-12-16 07:43 UTC, coderbot16 commented
Thanks for the PR! Looks like my initial comment was incorrect, upon another review this code looks good & should be a nice workaround for Origins on 1.16.